/*
 * JSP generated by Resin-3.0.28 (built Mon, 18 May 2009 02:16:38 PDT)
 */

package _jsp._web_22dinf._vistas;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.siagcee.logic.*;
import java.util.*;

public class _test__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
HttpSession sesion = request.getSession();
Administrador admin = (Administrador)sesion.getAttribute("administrador");
if(admin == null){

      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.forward("autenticar.do");
      if (true) return;
      out.write('\n');
      
}

      out.write(_jsp_string2, 0, _jsp_string2.length);
      


out.println("Resultado: <p /><br />");	
if (request.getAttribute("resultado") != null) {
	out.println(request.getAttribute("resultado") + "<br />");
}


      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4644494061398360982L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/vistas/test.jsp"), -3303173197959059753L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/vistas/admininicio.jsp"), -8379183646955275997L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/vistas/adminheader.jsp"), -2359136938021827160L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/vistas/adminfooter.jsp"), 119591587351550427L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string2 = "\n<html>\n	<head>\n		<META http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n		<title>SIAGCEE</title>\n		<link rel=\"stylesheet\" type=\"text/css\" href=\"comunes/css/micss.css\">\n	</head>\n\n<!--\n * Creado por F\u00c3\u00a1bio Pereira.\n * Bajo la tutor\u00c3\u00ada del Prof. Francisco Mirabal.\n * Trabajo Especial De Grado.\n * Licenciatura de Computaci\u00c3\u00b3n.\n * Universidad Central de Venezuela.\n * Fecha: 10/12/2009\n * Hora: 09:07:17 AM\n-->\n	<body>\r\n		<h1>SIAGCEE</h1>\r\n		<table cellpadding=\"4\" cellspacing=\"4\" border=\"0\" width=\"80%\">\r\n			<tr>\r\n				<td valign=\"top\">\r\n			\n\n".toCharArray();
    _jsp_string3 = "\n				</td>\r\n			</tr>\r\n		</table>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string0 = "\n\n\n<!--\n * Creado por F\u00e1bio Pereira.\n * Bajo la tutor\u00eda del Prof. Francisco Mirabal.\n * Trabajo Especial De Grado.\n * Licenciatura de Computaci\u00f3n.\n * Universidad Central de Venezuela.\n * Fecha: 10/12/2009\n * Hora: 09:07:17 AM\n-->\n".toCharArray();
    _jsp_string1 = "\n	".toCharArray();
  }
}
