/*
 * JSP generated by Resin-3.0.28 (built Mon, 18 May 2009 02:16:38 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;

public class _adminobjeto__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
   String usuario ="";
   HttpSession misesion = request.getSession(false);
   if(misesion.getAttribute("usuarioAutenticado") == null){
     
      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.forward("adminlogin.jsp", "error=" + ("Usuario no autenticado."));
      if (true) return;
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
   }else{
     usuario = (String)misesion.getAttribute("usuarioAutenticado");
   }


      out.write(_jsp_string2, 0, _jsp_string2.length);
      
  if (request.getAttribute("resultado") != null){
    out.println(request.getAttribute("resultado")+"<br />");
  }

      out.write(_jsp_string3, 0, _jsp_string3.length);
      
            ResultSet rs = (ResultSet)request.getAttribute("data");
            while(rs.next()){
              out.println("<option value='"+rs.getString("id_objeto")+"'>"+rs.getString("titulo")+"</option>");
              }
             
      out.write(_jsp_string4, 0, _jsp_string4.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4644494061398360982L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("adminobjeto.jsp"), -235342378126579483L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 4092044833529039094L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("menuadmin.jsp"), -8883645540559965403L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("footer.jsp"), -6520054440790214368L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "\r\n\r\n<html>\r\n    <title>SIAGCEE</title>\r\n\r\n    <body>\r\n        <h1>SIAGCEE</h1><br />\r\n        \r\n<table border =\"0\" cellpadding=\"4\" cellspacing=\"4\" border=\"0\">\r\n  <tr>\r\n    <td valign=\"top\">\r\n      <a href=\"admintabla.do\">Administrar Tablas</a><br />\r\n<a href=\"adminrenglon.do\">Administrar Renglones</a><br />\r\n<hr />\r\n<a href=\"adminobjeto.do\">Administrar Objetos</a><br />\r\n<a href=\"adminpregunta.do\">Administrar Preguntas</a><br />\r\n<hr />\r\n    </td>\r\n    <td valign=\"top\">\r\n        <h3>Administraci&oacute;n de objetos.</h3>\r\n\r\n".toCharArray();
    _jsp_string4 = "\r\n          </select>\r\n          <input type=\"submit\" value=\"eliminar\" name=\"eliminar\" />\r\n      </form>\r\n          <br><br>\r\n         Para agregar un objeto ind&iacute;quelo a continuaci&oacute;n.<br>\r\n         <table border=\"0\" cellspacing=\"4\" cellpadding=\"4\"><tr><td>\r\n      <form action=\"adminobjeto.do\" method=\"POST\">\r\n          <input type=\"hidden\" name=\"tipoform\" value=\"ingresar\">\r\n          Tipo de Objeto: </td><td><select name=\"tipoobjeto\">\r\n              <option value=\"C\">Censo</option>\r\n              <option value=\"E\">Encuesta</option>\r\n              <option value=\"CE\">Actualizaci&oacute;n de Censo</option>\r\n          </select></td></tr><tr><td>\r\n          T&iacute;tulo: </td><td><input type=\"text\" name=\"elemtoinsert\" value=\"\"></td></tr><tr><td>\r\n          Descripci&oacute;n: </td><td><textarea name=\"descripcion\" cols=\"40\" rows=\"10\"></textarea></td></tr><tr><td>\r\n          </td><td><input type=\"submit\" value=\"agregar\" name=\"agregar\" /></td></tr></table>\r\n      </form>\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n\r\n<br /><br />\r\n.-\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string1 = "\r\n     ".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
    _jsp_string3 = "\r\n<br>Si Desea Eliminar un objeto ind&iacute;quelo a continuaci&oacute;n.<br>\r\n      <form action=\"adminobjeto.do\" method=\"POST\">\r\n          <input type=\"hidden\" name=\"tipoform\" value=\"eliminar\">\r\n          <select name=\"elemtodelete\">\r\n            ".toCharArray();
  }
}
