/*
 * JSP generated by Resin-3.0.28 (built Mon, 18 May 2009 02:16:38 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _adminindex__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
   String usuario ="";
   HttpSession misesion = request.getSession(false);
   if(misesion.getAttribute("usuarioAutenticado") == null){
     
      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.forward("adminlogin.jsp", "error=" + ("Usuario no autenticado."));
      if (true) return;
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
   }else{
     usuario = (String)misesion.getAttribute("usuarioAutenticado");
   }


      out.write(_jsp_string2, 0, _jsp_string2.length);
      

/*
ResultSet rs = (ResultSet)request.getAttribute("data");

out.println("<table border=1><tr><th>nombre</th><th>tipo</th><th>comun</th></tr>");
while (rs.next())  {

  String a = rs.getString("pregunta");
  String b = rs.getString("tipopregunta");
  String c = rs.getString("comun");

  out.println("<tr><td>"+a+"</td><td>"+b+"</td><td>"+c+"</td></tr>");

}
out.println("</table>");
*/
  HttpSession sesion = request.getSession();
  String respuesta = (String)sesion.getAttribute("usuarioAutenticado");
  out.println(respuesta);


      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4644494061398360982L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("adminindex.jsp"), 3682130300748595587L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 4092044833529039094L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("menuadmin.jsp"), -8883645540559965403L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("footer.jsp"), -6520054440790214368L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "\r\n\r\n<html>\r\n    <title>SIAGCEE</title>\r\n\r\n    <body>\r\n        <h1>SIAGCEE</h1><br />\r\n        \r\n<table border =\"0\">\r\n  <tr>\r\n    <td valign=\"top\">\r\n      <a href=\"admintabla.do\">Administrar Tablas</a><br />\r\n<a href=\"adminrenglon.do\">Administrar Renglones</a><br />\r\n<hr />\r\n<a href=\"adminobjeto.do\">Administrar Objetos</a><br />\r\n<a href=\"adminpregunta.do\">Administrar Preguntas</a><br />\r\n<hr />\r\n    </td>\r\n    <td valign=\"top\">\r\n      Bienvenido\r\n".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string1 = "\r\n     ".toCharArray();
    _jsp_string3 = "\r\n. Seleccione una opci&oacute;n del men&uacute; lateral.\r\n    </td>\r\n  </tr>\r\n</table>\r\n\r\n\r\n<br /><br />\r\n.-\r\n</body>\r\n</html>\r\n".toCharArray();
  }
}
